# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DWM
email: dwm269@cornell.edu
description: >- # this means to ignore newlines until "baseurl:"
  David W. McKellar
  # I'm a PhD in the Biomedical Engineering Department at Cornell,
  # co-advised by Ben Cosgrove and Iwijn De Vlaminck. I work on computational
  # and molecular strategies to understand single-cell and spatial biology,
  # with particular interests in stem cells and noncoding RNAs.

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://mckellar.dw" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dwmckellar
github_username:  mckellardw

# Build settings
markdown: kramdown
# remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-feed
  - jekyll-font-awesome-sass
  # - jekyll-seo-tag


# theme: minima
remote_theme: jekyll/minima
jekyll/minima:
  skin: solarized
  social_links:
    - { platform: twitter,    user_url: "https://twitter.com/dwmckellar"}
    - { platform: github,     user_url: "https://github.com/mckellardw" }
    - { platform: orcid,      user_url: "https://orcid.org/0000-0002-7752-078X" }
    - { platform: linkedin,   user_url: "https://www.linkedin.com/in/dwmckellar/" }

show_excerpts: false

# font-awesome:
#   assets: true

# defaults:
#     values:
#       layout: "page"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
