
title: DWM
email: dmckellar@nygenome.org
description: >- # this means to ignore newlines until "baseurl:"
  David W. McKellar

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://mckellar.dw" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dwmckellar
github_username:  mckellardw

# Build settings
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-font-awesome-sass
  - jekyll-seo-tag

# theme: minima
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: twitter,    user_url: "https://twitter.com/dwmckellar"}
    - { platform: github,     user_url: "https://github.com/mckellardw" }
    - { platform: orcid,      user_url: "https://orcid.org/0000-0002-7752-078X" }
    - { platform: linkedin,   user_url: "https://www.linkedin.com/in/dwmckellar/" }
# github: mckellardw
# twitter: dwmckellar
# linkedin: dwmckellar
# orcid: orcid.org/0000-0002-7752-078X
show_excerpts: false

# font-awesome:
#   assets: true

# defaults:
#     values:
#       layout: "page"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
