
title: DWM
email: dmckellar@nygenome.org
description: >- # this means to ignore newlines until "baseurl:"
  David W. McKellar

# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://mckellar.dw" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dwmckellar
github_username:  mckellardw

# Build settings
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-font-awesome-sass
  - jekyll-seo-tag

# theme: minima
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: twitter,    user_url: "https://twitter.com/dwmckellar"}
    - { platform: github,     user_url: "https://github.com/mckellardw" }
    - { platform: orcid,      user_url: "https://orcid.org/0000-0002-7752-078X" }
    - { platform: linkedin,   user_url: "https://www.linkedin.com/in/dwmckellar/" }
    - { platform: bluesky,    user_url: "https://bsky.app/profile/dwmckellar.bsky.social" }

show_excerpts: false

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - backup_jekyll_site/
  - test/
  - README.md
