# Jekyll config
owner:
  name: David W. McKellar
  email: "dwm269@cornell.edu"
  description: personal site
  avatar: images/prof_pic.jpg
  twitter: dwmckellar
  github: mckellardw
  orcid: 0000-0002-7752-078X
url: "https://mckellardw.github.io/"
markdown: kramdown
highlighter: rouge
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
#   - jekyll-include-cache
# remote_theme: pages-themes/minimal@v0.2.0
theme: minima
minima:
  skin: dark
  social_links:
    twitter: dwmckellar
    github: mckellardw
# header_pages:
#   - cv/index.md
#   - album_lists/index.md
