# Jekyll config
name: David W. McKellar
description: personal site
url: "https://mckellardw.github.io/"
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
#   - jekyll-include-cache
# theme: minimal-mistakes-jekyll
highlighter: rouge
